;;;
{
    "pgotInclude" : [
        "global.got",
        "Makefile.src/mk-docMain.got",
        "Makefile.src/mk-mkFile.got",
        "Makefile.src/mk-lint.got",
        "Makefile.src/mk-todo.got"
    ]
}
;;;
.POSIX:

PNAME = repo-template

RTEMPLATE ?= .

all:

.PHONY: all

{{template "mk-docMain" .}}

{{template "mk-mkFile" .}}

{{template "mk-lint" .}}

{{template "mk-todo" .}}

# vim:set noet tw=80:
